package edu.mtu

interface MtuConstants {
    public static final BUILDINGS = [
            "01"   : "ADMIN" // "Administration Building"
            , "02" : "Electrical Substation"
            , "03" : "Lakeshore Center" // "Michigan Tech Lakeshore Center"
            , "04" : "ROTC" // "ROTC Building"
            , "05" : "Academic Offices Building"
            , "06" : "Annex Building"
            , "07" : "EERC" // "Electrical Energy Resources"
            , "08" : "DOW" // "DOW Envir Sciences & Engr Bldg"
            , "09" : "Alumni House"
            , "10" : "Rozsa" // "Rozsa Performing Arts & Educ"
            , "11" : "Walker" // "Walker - Arts & Humanities"
            , "12" : "M&M" // "Minerals & Materials Engr Bldg"
            , "13" : "Hamar House"
            , "14" : "Grover C. Dillman Hall"
            , "15" : "Fisher" //"Fisher Hall"
            , "16" : "Widmaier House"
            , "17" : "Library" // "J. R. Van Pelt Library"
            , "18" : "Forestry" // "U.J.Noblet Foresty Building"
            , "19" : "Chemical Sciences & Engr Bldg"
            , "20" : "MEEM" // "R. L. Smith (MEEM) Building"
            , "21" : "Volatile Liquid & Gases Bldg"
            , "22" : "Anderson House (Demolished)"
            , "23" : "Blanche Street House (Sold)"
            , "24" : "SDC" // "Student Development Complex"
            , "25" : "Sherman Field Press Box"
            , "26" : "MTN Uplink Equipment Bldg"
            , "27" : "Ford Forestry Center"
            , "28" : "Rekhi" // "Kanwal and Ann Rekhi Hall"
            , "29" : "Franklin Square"
            , "30" : "Little Huskies Child Care"
            , "31" : "DHH" // "Douglass Houghton Hall"
            , "32" : "Daniell Heights Apartments"
            , "33" : "Daniell Heights Housing Shop"
            , "34" : "MUB" // "Memorial Union Building"
            , "35" : "Daniell Heights Nursery"
            , "36" : "Tech House (Abbey House)"
            , "37" : "WADS" // "Wadsworth Hall"
            , "38" : "West McNair Hall"
            , "39" : "McNair Hall Food Services"
            , "40" : "East McNair Hall"
            , "41" : "Central Heating Plant"
            , "42" : "Facilities Management Storage"
            , "43" : "Lakeside Laboratory (Demolished)"
            , "44" : "Facilities Building"
            , "45" : "Kettle-Gundlach House"
            , "46" : "Nordic Ski Waxing Center"
            , "47" : "217 East Street (previously Vivian House)"
            , "48" : "Hillside Place"
            , "49" : "Waste Mgmt Resrces Recvry Bldg"
            , "50" : "Gates Tennis Center"
            , "51" : "O'Connor House (Meyer House)"
            , "52" : "Portage Lake Golf Course"
            , "53" : "Mont Ripley Ski Hill"
            , "54" : "Mont Ripley Ski Chalet"
            , "55" : "Mont Ripley Storage Building"
            , "56" : "Daniell Heights Storage Bldg"
            , "57" : "209 East Street (previously  Hagen House)"
            , "58" : "Golf Course Buildings"
            , "59" : "Golf Course Buildings"
            , "60" : "Golf Course Buildings"
            , "61" : "Golf Course Buildings"
            , "62" : "Golf Course Buildings"
            , "63" : "Golf Course Buildings"
            , "64" : "Golf Course Buildings"
            , "65" : "Daniell Heights Storage Building"
            , "66" : "Nordic Ski Timing Bldg"
            , "67" : "Nordic Ski Warmup Bldg"
            , "68" : "SDC Storage Building"
            , "69" : "KRC Buildings"
            , "70" : "KRC Buildings"
            , "71" : "KRC Buildings"
            , "72" : "KRC Buildings"
            , "73" : "KRC Buildings"
            , "74" : "KRC Buildings"
            , "75" : "KRC Buildings"
            , "76" : "KRC Buildings"
            , "77" : "KRC Buildings"
            , "78" : "KRC Buildings"
            , "79" : "KRC Buildings"
            , "80" : "KRC Buildings"
            , "81" : "Power Generation Building"
            , "82" : "Honors House (previously Gundlach House (Ruppe))"
            , "83" : "Fitzpatrick House (Demolished)"
            , "84" : "Meese" // "Harold Meese Center"
            , "85" : "Fire Hall Building (Sold)"
            , "86" : "MTU Tower Building"
            , "87" : "Granters Marine (Sold)"
            , "88" : "Chemical Storage Building"
            , "89" : "MTU Ski Trail Groomer Storage"
            , "90" : "Sands Pilot Plant"
            , "91" : "WGGL Transmitter Building (Sold)"
            , "92" : "Alternative Enrgy Rsch Bldg"
            , "93" : "Fish Hatchery Building"
            , "94" : "AMJOCH Observatory"
            , "95" : "ATDC"
            , "96" : "Portage Lake Vault"
            , "98" : "Off Campus Sites"
            , "99" : "Miscellaneous Bldg Sites"
            , "100": "GLRC" // "Great Lakes Research Center"
            , "101": "Nordic Ski Storage"
            , "102": "Advncd Power Systms Rsch Cntr"
            , "103": "A.E. Seaman Mineral Museum"
            , "104": "Mineral Museum Storage"
            , "105": "KRC Cold Storage"
            , "106": "Sands Storage"
            , "107": "212 East Street (previously Peace Lockhart House)"
            , "108": "KRC Inspection Pit Building"
            , "109": "Mt Ripley Pump House"
            , "110": "214 East Street (previously Larson House)"
            , "111": "Theta Tau House"
            , "112": "Facilities Storage"
            , "801": "SDC Soccer Fields"
            , "802": "Sherman Field"
            , "803": "Disc Golf Course"
            , "804": "Recreational Sports Fields"
            , "805": "Broomball Courts"
            , "806": "Parking Lot 21"
            , "901": "USDA Forest Service"
            , "903": "Hancock Storage (Edward Jones)"
            , "905": "Huntington National Bank Bldg"
            , "906": "MTRI"
            , "907": "Sharon Avenue Storage"
    ]

    public static final COURSE_SUBJECTS = [
            "ACC"   : "Accounting"
            , "AF"  : "Air Force ROTC"
            , "AR"  : "Army ROTC"
            , "BE"  : "Biomedical Engineering"
            , "BL"  : "Biological Sciences"
            , "BUS" : "Business"
            , "CEE" : "Civil and Environmental Engineering"
            , "CH"  : "Chemistry"
            , "CM"  : "Chemical Engineering"
            , "CMG" : "Construction Management"
            , "CS"  : "Computer Science"
            , "EC"  : "Economics"
            , "ED"  : "Education"
            , "EE"  : "Electrical Engineering"
            , "EET" : "Electrical Engineering Technology"
            , "ENG" : "Engineering Fundamentals"
            , "ENT" : "Enterprise"
            , "ESL" : "English as a Second Language"
            , "FIN" : "Finance"
            , "FW"  : "Forest Resources and Environmental Science"
            , "GE"  : "Geological and Mining Engineering and Sciences"
            , "HON" : "Honors, Pavlis"
            , "HU"  : "Humanities"
            , "EH"  : "Kinesiology and Integrative Physiology"
            , "MA"  : "Mathematical Sciences"
            , "MEEM": "Mechanical Engineering–Engineering Mechanics"
            , "MET" : "Mechanical Engineering Technology"
            , "MGT" : "Management"
            , "MIS" : "Management Information Systems"
            , "MKT" : "Marketing"
            , "MY"  : "Materials Science and Engineering"
            , "OSM" : "Operations and Supply Chain Management"
            , "PE"  : "Physical Education"
            , "PH"  : "Physics"
            , "PSY" : "Psychology"
            , "SA"  : "Sciences and Arts"
            , "SAT" : "Systems Admin. Technology"
            , "SS"  : "Social Sciences"
            , "SU"  : "Surveying"
            , "TE"  : "Technology"
            , "UN"  : "University Wide"
            , "FA"  : "Visual and Performing Arts"
    ]

    public static final LANGUAGES = [
            "Assembly"
            , "C"
            , "C++"
            , "C#"
            , "Go"
            , "HTML5"
            , "Haskell"
            , "Java"
            , "Lisp"
            , "Prolog"
            , "Python"
            , "R"
            , "Racket"
            , "Scheme"
            , "Snap!"
    ]

}