---
grails:
    profile: web
    codegen:
        defaultPackage: queue3
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'

# 2018-07-28 ureel - set session timeout
server:
    session:
        timeout: 3600  #seconds

# 2018-08-17 ureel
logging:
    file: '@info.app.name@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
                - text/html
                - application/xhtml+xml
            js: text/javascript
            json:
                - application/json
                - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
                - application/hal+json
                - application/hal+xml
            xml:
                - text/xml
                - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    # 2018-07-16 ureel: default values
    #    pooled: true
    #    jmxExport: true
    #    driverClassName: org.h2.Driver
    #    username: sa
    #    password: ''

    # 2018-07-16 ureel
    pooled: true
    jmxExport: true
    username: root
    # password: agOdnek2

environments:
    # 2018-07-16 ureel: Support for PC with Grails and MySQL Database
    development:
        dataSource:
            dbCreate: update
            driverClassName: com.mysql.cj.jdbc.Driver
            # driverClassName: org.mariadb.jdbc.Driver
            # dialect: "org.hibernate.dialect.MariaDB53Dialect"
            # dialect: "org.hibernate.dialect.MySQL57Dialect"
            dialect: "org.hibernate.dialect.MySQLDialect"
            #      url: jdbc:mysql://localhost:3306/webta?autoReconnect=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=US/Eastern
            url: jdbc:mysql://localhost:3306/webta?autoReconnect=true&useSSL=false
            password: asdf1234
            properties:
                pooled: true
                jmxEnabled: true
                initialSize: 20 # 5
                maxActive: 1000 # 50
                minIdle: 20 # 5
                maxIdle: 100 # 25
                maxWait: 30000 # 10000
                maxAge: 600000 # 600000 milliseconds = 10 minutes
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
                # 2018-08-10 ureel
                removeAbandoned: true
                removeAbandonedTimeout: 300 # 300 seconds = 5 min
                suspectTimeout: 150 # 150 seconds = 2.5 minutes
                logAbandoned: true # Do not use in production!
                logValidationErrors: true # Do not use in production!

    # 2018-07-16 ureel: Support for Test Environment with Grails and MySQL Database
    test:
        dataSource:
            dbCreate: update
            driverClassName: com.mysql.jdbc.Driver
            # driverClassName: org.mariadb.jdbc.Driver
            # dialect: "org.hibernate.dialect.MariaDB53Dialect"
            # dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
            # dialect: "org.hibernate.dialect.MySQL57Dialect"
            dialect: "org.hibernate.dialect.MySQLDialect"
            # url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            url: jdbc:mysql://localhost:3306/webta?autoReconnect=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=US/Eastern
            password: KzAGY!P4ZXqH
            properties:
                pooled: true
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

    # 2018-07-16 ureel
    production:
        dataSource:
            dbCreate: none
            driverClassName: com.mysql.jdbc.Driver
            # driverClassName: org.mariadb.jdbc.Driver
            # dialect: "org.hibernate.dialect.MariaDB53Dialect"
            # dialect: "org.hibernate.dialect.MySQL57Dialect"
            dialect: "org.hibernate.dialect.MySQLDialect"
            # url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            # url: jdbc:mysql://localhost:3306/webta?autoReconnect=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=US/Eastern
            url: jdbc:mysql://localhost:3306/webta?autoReconnect=true&useSSL=false
            #    url: jdbc:mariadb://localhost:3306/webta
            password: KzAGY!P4ZXqH
            properties:
                #       pool: false # true
                #       jmxEnabled: false # true
                #       maxIdleTime: 60
                #       # useResetConnection: true # false
                #       staticGlobal: true
                #       time_zone: US/Eastern
                #       # useUnicode: true
                pooled: true
                jmxEnabled: true
                initialSize: 20 # 5
                maxActive: 1000 # 50
                minIdle: 20 # 5
                maxIdle: 100 # 25
                maxWait: 30000 # 10000
                maxAge: 600000 # 600000 milliseconds = 10 minutes
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
                # 2018-08-10 ureel
                removeAbandoned: true
                removeAbandonedTimeout: 300 # 300 seconds = 5 min
                suspectTimeout: 150 # 150 seconds = 2.5 minutes


#            dbCreate: none
#            driverClassName: org.mariadb.jdbc.Driver
#            dialect: "org.hibernate.dialect.MariaDB53Dialect"
#            # url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#            # url: jdbc:mysql://localhost:3306/webta?autoReconnect=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=US/Eastern
#            url: jdbc:mariadb://localhost:3306/webta
#            properties:
#                pool: false # true
#                jmxEnabled: false # true
#                maxIdleTime: 60
#                # useResetConnection: true # false
#                staticGlobal: true
#                time_zone: US/Eastern
#                # useUnicode: true

# 2018-08-19 ureel
#hibernate:
#    cache:
#        queries: false
#        use_second_level_cache: false
#        use_query_cache: false
#dataSource:
#    pooled: true
#    jmxExport: true
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#
#environments:
#    development:
#        dataSource:
#            dbCreate: create-drop
#            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#    test:
#        dataSource:
#            dbCreate: update
#            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#    production:
#        dataSource:
#            dbCreate: none
#            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#            properties:
#                jmxEnabled: true
#                initialSize: 5
#                maxActive: 50
#                minIdle: 5
#                maxIdle: 25
#                maxWait: 10000
#                maxAge: 600000
#                timeBetweenEvictionRunsMillis: 5000
#                minEvictableIdleTimeMillis: 60000
#                validationQuery: SELECT 1
#                validationQueryTimeout: 3
#                validationInterval: 15000
#                testOnBorrow: true
#                testWhileIdle: true
#                testOnReturn: false
#                jdbcInterceptors: ConnectionState
#                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
